language: node_js
node_js: "10"
jobs:
  include:
    - stage: "Server Tests"
      services:
        postgresql
      before_script:
        - ./scripts/initDb.js test
      script: yarn test
    - stage: "Unit Tests"
      before_script: cd client
      script: yarn install && yarn test
    - stage: "Integration Tests"
      before_script: cd client
      script: yarn install && yarn integration